### PR TITLE
What para

### PR DESCRIPTION
**Pull request by faph**
Tweaks to what paragraphs

### CODE REVIEW

**Comment by faph** [comment]
I think removing "literally" should do it. You're right that technically it could be 2 clicks (if you're not touching the keyboard).

**Comment by faph** [comment]
Please do feel free to drop the italics. I think by capitalising it's clear that this is a name.

**Comment by faph** [comment]
A "recent updates" example is in the final sentence. Not sure if you want to move/rephrase that. Remember we also refer to recent updates in the very first sentence of the article.

**Comment by mikerspencer** [comment]
It's ambiguous without a ref. I'm happy repeating the later ref. I'll update.

**Pull request merged**
